node {
   def commit_id
   try {
     stage('Preparation') { // for display purposes
        // Get some code from a GitHub repository
        git 'https://github.com/Taurin190/php-simple-app.git'
        sh "git rev-parse --short HEAD > .git/commit-id"
        commit_id = readFile('.git/commit-id').trim()
     }
     stage('docker build/push') {
        docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
            def app = docker.build("taurin189/php-simple:${commit_id}", '.').push()
        }
        
        slackSend ( message: "SUCCESS: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' PASS Build-Docker")
     }
   } catch(e) {
       currentBuild.result = "FAILURE";
       slackSend (color: '#FF0000', message: "FAILED: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}] ${e}' (${env.BUILD_URL})")
       
       throw e
   }
}