node {
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/Taurin190/blog-springboot.git'

   }
   stage('Test') {
       sh "./gradlew test"
   }
   stage('Build') {
      sh "./gradlew build"
   }
}